<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RootNamespace>MeridianTestContracts</RootNamespace>
    <AssemblyName>MeridianTestContracts</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MeridianRequestSystem\MeridianRequestSystem\MeridianRequestSystem.csproj" />
  </ItemGroup>

</Project>
